### ISSUE TITLE
Graph QL + React.js

### ISSUE THREAD

**Issue by melvinodsa** [shredx/plans#3]
## Simple E-Commerce platform using GraphQL at the backend and React.js at the frontend
Idea is to get hands-on on building a platform in [react.js](https://reactjs.org/) for frontend developers and [Golang](https://golang.org)/[Node.js](https://nodejs.org/en/)/[Python](https://www.python.org/). It is an opportunity to get familiarized with GraphQL for both of the camps. It will enable the devs of multiple fraternities to come together and build something cool and tangible. 

## Overview
The platform can is divided into three parts.
* CMS frontend - **React.js**
* Storefront frontend - **React.js**
* Backend for CMS and Storefront - **Golang** / **Node.js** / **Python**

## Takeaways
* You will get hands-on on working for cross-functional teams.
* Get code experience solving the various problems like user management, caching, etc.
* Building scalable API
* Intro to GraphQL
* Hands-on NGINX, Docker for packaging the application

## Location
[myHQ](https://myhq.in/) coworking space. They have a one-day [free trial](https://myhq.in/free-trial). If the number of participants is limited, we can host shredx in someone's home too.

**Comment by ashokdey** [comment]
Kudos to @melvinodsa for coming up with a new episode 🎈 

However, I have a few changes to this proposal. `GraphQL` is extensive and the same for `React.js`

This proposal can be split into 2 independent episodes covering the following for the first part:

## GraphQL

- What, when why
- Query, Resolvers & Fragments
- `GraphiQL`
- Mutations
- Subscriptions
- Authentication
- Dataloader
- Interfacing with MySQL/PostgreSQL/MongoDB/Redis
- Using any of these languages Node.js/Golang/Python

<sup>*</sup> Now you may be thinking that the GraphQL Episode can also be further splitted into 2 sessions 😆

**Comment by melvinodsa** [comment]
Yeah, GraphQL is a vast topic same as react. 

My initial idea was to build something **in parallel** with 
* frontend folks concentrating on 
  - building an awesome react app 
  - getting little hands-on GraphQL integration.
* Backend devs can concentrate on GraphQL extensively and develop an application on top of it.

Episode two can be like an intro to GraphQL literature and can have a future session for advance/moderate topics in GraphQL as the **follow-up**.

**Comment by ekas** [comment]
We could simply start with a simple Node Boilerplate and Step and Step integrate GraphQL with a playground and then React over it. And moving on further we can even build it further with Angular, VueJS and even Spring Boot

**Comment by ashokdey** [comment]
> Yeah, GraphQL is a vast topic same as react.
> 
> My initial idea was to build something **in parallel** with
> 
> * frontend folks concentrating on
>   
>   * building an awesome react app
>   * getting little hands-on GraphQL integration.
> * Backend devs can concentrate on GraphQL extensively and develop an application on top of it.
> 
> Episode two can be like an intro to GraphQL literature and can have a future session for advance/moderate topics in GraphQL as the **follow-up**.

@melvinodsa this would be great if we can make it feasible. Also, we should focus more on the integration of GraphQL with different databases and different languages

- Redis, Golang, GraphQL
- MongoDB, Golang, GraphQL
- Redis, Node.js, GraphQL

Also @ekas, I guess if you are talking about setting up a node boilerplate project then let us know if you already have something in mind for the boilerplate, alternatively you can have a look at:

- **Template from Scratch (Only Node.js)**: [node-api-template](https://github.com/knaxus/node-api-template)
- **Template with MySQL & GraphQL**: [rest-and-graphql](https://github.com/knaxus/rest-and-graphql) this is the one I presented for the basic GraphQL talk

I can connect to Gaurav Sehrawat if he can remotely assist or like to guide all of you with Node.js/GrapgQL

**Comment by ashokdey** [comment]
@melvinodsa: Go ahead to frame the tasks in the project for GraphQL. Here:  https://github.com/shredx/plans/projects/3

**Comment by melvinodsa** [comment]
I have allocated the project tasks. Let me know if any changes are required.

MongoDB drivers are available for both Golang and Node.js.
Integrating these drivers with GraphQL is going to be crucial(😄 That is the only painful part since coming from REST-like ecosystem).

Yes we can use the API templates that we already used for Episode 1
* [Node.js Rate limiter](https://github.com/knaxus/node-api-template)
* [Golang Rate limiter](https://revel.github.io/tutorial/index.html)

**Comment by harpreetkhalsagtbit** [comment]
> ## Simple E-Commerce platform using GraphQL at the backend and React.js at the frontend
> Idea is to get hands-on on building a platform in [react.js](https://reactjs.org/) for frontend developers and [Golang](https://golang.org)/[Node.js](https://nodejs.org/en/)/[Python](https://www.python.org/). It is an opportunity to get familiarized with GraphQL for both of the camps. It will enable the devs of multiple fraternities to come together and build something cool and tangible.
> 
> ## Overview
> The platform can is divided into three parts.
> 
> * CMS frontend - **React.js**
> * Storefront frontend - **React.js**
> * Backend for CMS and Storefront - **Golang** / **Node.js** / **Python**
> 
> ## Takeaways
> * You will get hands-on on working for cross-functional teams.
> * Get code experience solving the various problems like user management, caching, etc.
> * Building scalable API
> * Intro to GraphQL
> * Hands-on NGINX, Docker for packaging the application
> 
> ## Location
> [myHQ](https://myhq.in/) coworking space. They have a one-day [free trial](https://myhq.in/free-trial). If the number of participants is limited, we can host shredx in someone's home too.

I am interested for this. May I know the date, so that I can plan accordingly.

**Comment by melvinodsa** [comment]
We are conducting it on 30-March-2019. It will happen in Gurgaon. Since the number of participants is limited, we are thinking about getting together in one of our's apartment. You can DM in twitter for more info https://twitter.com/melvinodsa.

**Comment by ashokdey** [comment]
@all We are going with the Golang + GraphQL today. Frontend guys are also on the way. have a blast 🔥 

Thanks a lot @melvinodsa

**Comment by prateek951** [comment]
@ashokdey So we would be using React Apollo, Apollo Client with GRAPHQL?

**Comment by ashokdey** [comment]
> @ashokdey So we would be using React Apollo, Apollo Client with GRAPHQL?

@prateek951, @melvinodsa can answer it better. Also, have a look at the associated project here: [GraphQL Project](https://github.com/shredx/plans/projects/3)

**Comment by souravdasslg** [comment]
Is it still going on?

**Comment by ashokdey** [comment]
Hello @souravdasslg, its over now.
