### ISSUE TITLE
Slack channel link is not working!

### ISSUE THREAD

**Issue by vinitshahdeo** [shredx/plans#8]
**The [given link](https://bit.ly/2CHbXos) for joining Slack chat is not active.**

Please check.

<img width="1437" alt="Screenshot 2019-10-03 at 11 46 57 PM" src="https://user-images.githubusercontent.com/20594326/66152946-2da73280-e638-11e9-9784-9088f085af40.png">

**Comment by ashokdey** [comment]
Thanks @vinitshahdeo, I will update the URL

**Comment by ashokdey** [comment]
I have updated the link to join the slack team. 🍷
